language: go
go:
 - 1.3
 - tip
install:
  - echo $GOPATH
  - go get github.com/asaskevich/govalidator
  - go get github.com/aws/aws-sdk-go
  - go get github.com/Azure/go-ansiterm
  - go get github.com/davecgh/go-spew
  - go get github.com/get3w/get3w-sdk-go
  - go get github.com/google/go-querystring
  - go get github.com/pmezard/go-difflib
  - go get github.com/russross/blackfriday
  - go get github.com/satori/go.uuid
  - go get github.com/shurcooL/sanitized_anchor_name
  - go get github.com/Sirupsen/logrus
  - go get github.com/stretchr/testify
  - go get github.com/vaughan0/go-ini
  - go get gopkg.in/yaml.v2
  - go get github.com/mitchellh/gox
  - go install
script: go test -v ./...
